// English Privacy Policy Content
const privacyen = {
    title: 'Privacy Policy',
    lastUpdated: 'Last Updated: January 13, 2025',
    backToHome: '← Back to Home',
    pageTitle: 'Privacy Policy - PULSE',
    mainContent: `
        <h1>Privacy Policy</h1>
        <p><strong>Last Updated: January 13, 2025</strong></p>
        
        <!-- Table of Contents -->
        <div class="toc">
            <h3>Table of Contents</h3>
            <ul>
                <li><a href="#introduction">1. Introduction</a></li>
                <li><a href="#data-collection">2. Information We Collect</a></li>
                <li><a href="#data-usage">3. How We Use Your Information</a></li>
                <li><a href="#third-party">4. Third-Party Services</a></li>
                <li><a href="#data-retention">5. Data Retention</a></li>
                <li><a href="#user-rights">6. Your Rights</a></li>
                <li><a href="#data-security">7. Data Security</a></li>
                <li><a href="#international-transfers">8. International Data Transfers</a></li>
                <li><a href="#children-privacy">9. Children's Privacy</a></li>
                <li><a href="#stripe-payments">10. Stripe Payment Processing</a></li>
                <li><a href="#ai-processing">11. AI Data Processing</a></li>
                <li><a href="#policy-changes">12. Privacy Policy Changes</a></li>
                <li><a href="#contact">13. Contact Us</a></li>
            </ul>
        </div>
        
        <h2 id="introduction">1. Introduction</h2>
        <p>Welcome to PULSE, an AI-powered news alert application. This privacy policy explains how we collect, use, store, and protect your personal information. We are committed to protecting your privacy and complying with relevant data protection laws, including the European Union General Data Protection Regulation (GDPR) and the California Consumer Privacy Act (CCPA).</p>
        
        <h2 id="data-collection">2. Information We Collect</h2>
        <h3>2.1 Account Information</h3>
        <p>When you create a PULSE account, we collect:</p>
        <ul>
            <li>Email address (for account creation and communication)</li>
            <li>User ID (generated by AWS Cognito)</li>
            <li>Account preferences</li>
        </ul>
        
        <h3>2.2 Device Information</h3>
        <ul>
            <li>Device identifiers</li>
            <li>Operating system version</li>
            <li>Application version</li>
            <li>Push notification tokens (iOS/Android)</li>
            <li>Timezone and region information</li>
        </ul>
        
        <h3>2.3 Usage Data</h3>
        <ul>
            <li>Reading preferences and habits</li>
            <li>Application interaction patterns</li>
            <li>News reading history (retained for 7 days)</li>
            <li>Feature usage statistics</li>
        </ul>
        
        <h3>2.4 Payment Information</h3>
        <p>Payment is processed entirely by Stripe. We do not receive or store your credit card information, only transaction IDs and subscription status.</p>
        
        <h2 id="data-usage">3. How We Use Your Information</h2>
        <p>We use your personal information based on the following legal bases:</p>
        
        <h3>3.1 Contract Necessity</h3>
        <ul>
            <li>Provide news alert services</li>
            <li>Manage your account and subscription</li>
            <li>Process payments (through Stripe)</li>
            <li>Send push notifications</li>
        </ul>
        
        <h3>3.2 Legitimate Interests</h3>
        <ul>
            <li>Improve service quality</li>
            <li>Prevent fraud</li>
            <li>Technical support</li>
            <li>Service analytics</li>
        </ul>
        
        <h3>3.3 Consent</h3>
        <ul>
            <li>Send marketing communications (you can opt out at any time)</li>
            <li>Push notifications (can be managed in settings)</li>
            <li>Optional features</li>
        </ul>
        
        <h2 id="third-party">4. Third-Party Services</h2>
        <p>We work with the following third-party service providers:</p>
        
        <h3>4.1 AWS (Amazon Web Services)</h3>
        <p>Cloud hosting and data storage services, located in the US East region.</p>
        
        <h3>4.2 OpenAI</h3>
        <p>AI news summarization and translation services.</p>
        
        <h3>4.3 Stripe</h3>
        <p>Payment processing services, handling all subscriptions and transactions.</p>
        
        <h3>4.4 Push Notification Services</h3>
        <ul>
            <li>Apple Push Notification Service (iOS)</li>
            <li>Firebase Cloud Messaging (Android)</li>
        </ul>
        
        <h3>4.5 News Content Providers</h3>
        <ul>
            <li>MediaStack</li>
            <li>RapidAPI</li>
        </ul>
        
        <h2 id="data-retention">5. Data Retention</h2>
        <ul>
            <li><strong>Account data:</strong> Duration of account validity</li>
            <li><strong>Payment records:</strong> Handled by Stripe according to their retention policy</li>
            <li><strong>Usage data:</strong> 2 years (for service improvement)</li>
            <li><strong>News reading history:</strong> 7 days (automatically deleted)</li>
            <li><strong>Push notification tokens:</strong> Until device unregistration</li>
            <li><strong>Deleted accounts:</strong> Immediately and permanently deleted, cannot be recovered</li>
        </ul>
        
        <h2 id="user-rights">6. Your Rights</h2>
        <p>Under GDPR and CCPA, you have the following rights:</p>
        
        <h3>6.1 Right of Access</h3>
        <p>You have the right to request access to personal data we hold about you.</p>
        
        <h3>6.2 Right to Rectification</h3>
        <p>You can update your personal information through the app or email.</p>
        
        <h3>6.3 Right to Erasure ("Right to be Forgotten")</h3>
        <p>You can request deletion of your personal data. Please note:</p>
        <ul>
            <li>Account deletion is permanent and cannot be recovered</li>
            <li>Please send an email to support@pulse-news.app</li>
            <li>Deletion will be executed immediately with no grace period</li>
        </ul>
        
        <h3>6.4 Right to Data Portability</h3>
        <p>You can request to export your data in machine-readable format.</p>
        
        <h3>6.5 Right to Object to Processing</h3>
        <p>You can object to our data processing based on legitimate interests.</p>
        
        <h3>6.6 Right to Withdraw Consent</h3>
        <p>You can withdraw consent for data processing at any time.</p>
        
        <p><strong>To exercise your rights:</strong><br>
        Please send an email to support@pulse-news.app, and we will respond to your request within 30 days.</p>
        
        <h2 id="data-security">7. Data Security</h2>
        <p>We implement industry-standard security measures to protect your personal information:</p>
        <ul>
            <li>All data is encrypted during transmission and at rest</li>
            <li>Access control and authentication</li>
            <li>Regular security audits</li>
            <li>Employee data protection training</li>
            <li>Incident response procedures</li>
        </ul>
        
        <h2 id="international-transfers">8. International Data Transfers</h2>
        <p>Your data may be transferred to regions outside your country:</p>
        <ul>
            <li>Primary data storage is in AWS US East region</li>
            <li>Data from EU users may be transferred to the United States</li>
            <li>We ensure appropriate safeguards are in place</li>
            <li>Compliance with standard contractual clauses</li>
        </ul>
        
        <h2 id="children-privacy">9. Children's Privacy</h2>
        <p>PULSE is not intended for children under 13 years old (under 16 in the EU). We do not knowingly collect personal information from minors. If you are a parent and discover that your child has provided personal information to us, please contact us to delete that information.</p>
        
        <h2 id="stripe-payments">10. Stripe Payment Processing</h2>
        <p>All payments are processed by Stripe:</p>
        <ul>
            <li>We never receive or store credit card information</li>
            <li>Stripe's privacy policy applies to payment data</li>
            <li>We only receive transaction IDs and subscription status</li>
            <li>Payment data retention is handled by Stripe according to PCI compliance requirements</li>
            <li>Refund processing is handled through email case-by-case</li>
        </ul>
        
        <h2 id="ai-processing">11. AI Data Processing</h2>
        <p>We use AI technology to provide services:</p>
        <ul>
            <li>OpenAI processes news for summarization and translation</li>
            <li>AI identifies news importance levels</li>
            <li>No automated decision-making affecting user rights</li>
            <li>AI classification system has human oversight</li>
            <li>No profiling of personal data for marketing purposes</li>
        </ul>
        
        <h2 id="policy-changes">12. Privacy Policy Changes</h2>
        <p>We may update this privacy policy from time to time:</p>
        <ul>
            <li>Major changes will be notified via email</li>
            <li>Changes will be posted on the website</li>
            <li>We recommend reviewing this policy regularly</li>
            <li>Continued use of the service indicates acceptance of changes</li>
        </ul>
        
        <h2 id="contact">13. Contact Us</h2>
        <p>If you have any questions about this privacy policy or need to exercise your rights, please contact us through the following methods:</p>
        
        <p><strong>Email:</strong> support@pulse-news.app<br>
        <strong>Website:</strong> https://pulse-news.app<br>
        <strong>Response Time:</strong> We will respond to your request within 30 days</p>
        
        <div class="last-updated">
            <p><em>This privacy policy was last updated on January 13, 2025</em></p>
        </div>
    `
};

// Make sure the variable is available globally
window.privacyen = privacyen;

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = privacyen;
}